package zkc

const (
	MethodZkevmBatchNumber              = "zkevm_batchNumber"
	MethodZkevmBatchNumberByBlockNumber = "zkevm_batchNumberByBlockNumber"
	MethodZkevmConsolidatedBlockNumber  = "zkevm_consolidatedBlockNumber"
	MethodZkevmEstimateCounters         = "zkevm_estimateCounters"
	MethodZkevmGetBatchByNumber         = "zkevm_getBatchByNumber"
	MethodZkevmGetBatchCountersByNumber = "zkevm_getBatchCountersByNumber"
	MethodZkevmGetBatchWitness          = "zkevm_getBatchWitness"
	MethodZkevmGetBlockRangeWitness     = "zkevm_getBlockRangeWitness"
	MethodZkevmGetExitRootTable         = "zkevm_getExitRootTable"
	MethodZkevmGetExitRootsByGER        = "zkevm_getExitRootsByGER"
	MethodZkevmGetForkById              = "zkevm_getForkById"
	MethodZkevmGetForkId                = "zkevm_getForkId"
	MethodZkevmGetForkIdByBatchNumber   = "zkevm_getForkIdByBatchNumber"
	MethodZkevmGetForks                 = "zkevm_getForks"
	MethodZkevmGetFullBlockByHash       = "zkevm_getFullBlockByHash"
	MethodZkevmGetFullBlockByNumber     = "zkevm_getFullBlockByNumber"
	MethodZkevmGetL2BlockInfoTree       = "zkevm_getL2BlockInfoTree"
	MethodZkevmGetLatestDataStreamBlock = "zkevm_getLatestDataStreamBlock"
	MethodZkevmGetLatestGlobalExitRoot  = "zkevm_getLatestGlobalExitRoot"
	MethodZkevmGetProverInput           = "zkevm_getProverInput"
	MethodZkevmGetRollupAddress         = "zkevm_getRollupAddress"
	MethodZkevmGetRollupManagerAddress  = "zkevm_getRollupManagerAddress"
	MethodZkevmGetVersionHistory        = "zkevm_getVersionHistory"
	MethodZkevmGetWitness               = "zkevm_getWitness"
	MethodZkevmIsBlockConsolidated      = "zkevm_isBlockConsolidated"
	MethodZkevmIsBlockVirtualized       = "zkevm_isBlockVirtualized"
	MethodZkevmVerifiedBatchNumber      = "zkevm_verifiedBatchNumber"
	MethodZkevmVirtualBatchNumber       = "zkevm_virtualBatchNumber"
)
